SWIDEA_SITE/server/apps/devtool_posts/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'

urlpatterns = [
  path('/list', list, name='list'),
  path('/create', create, name='create'),
  path('/detail/<int:pk>', detail, name='detail'),
  path('/delete/<int:pk>', delete, name='delete'),
  path('/update/<int:pk>', update, name='update'),
]

SWIDEA_SITE/server/apps/idea_posts/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
  path('', main, name='main'),
  path('create/', create, name='create'),
  path('detail/<int:pk>/', detail, name='detail'),
  path('delete/<int:pk>/', delete, name='delete'),
  path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/server/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.idea_posts.urls')),
    path('devtools', include('apps.devtool_posts.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/server/apps/devtool_posts/models.py
from django.db import models

class DevtoolPost(models.Model):
    name = models.CharField('이름', max_length=30)
    kind = models.CharField('종류', max_length=30)
    content = models.TextField('개발툴 설명', max_length=100)
    ideas = models.ManyToManyField('idea_posts.IdeaPost', related_name='related_devtools')

    def __str__(self):
        return self.name

SWIDEA_SITE/server/apps/idea_posts/models.py
from django.db import models
from apps.devtool_posts.models import DevtoolPost

class IdeaPost(models.Model):
  title = models.CharField('아이디어명', max_length=50)
  content = models.TextField('아이디어 설명', max_length=100)
  # devtool
  devtools_id = models.ForeignKey(DevtoolPost, on_delete=models.CASCADE, related_name='related_ideas', default=1)
  interest = models.IntegerField('관심도', default=0)
  # 이미지
  image = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')

  # 생성 시각, 수정 시각
  created_date = models.DateTimeField('작성일', auto_created=True, auto_now_add=True)
  updated_date = models.DateTimeField('수정일', auto_created=True, auto_now=True)

  def __str__(self):
    return self.title

SWIDEA_SITE/server/apps/devtool_posts/forms.py
from django import forms
from .models import DevtoolPost

class DevtoolPostForm(forms.ModelForm):
  class Meta():
    model = DevtoolPost
    fields = ['name', 'kind', 'content']

SWIDEA_SITE/server/apps/idea_posts/forms.py
from django import forms
from .models import IdeaPost
from apps.devtool_posts.models import DevtoolPost

class IdeaPostForm(forms.ModelForm):
  devtools = forms.ModelChoiceField(queryset=DevtoolPost.objects.all(), widget=forms.Select, label="예상 개발툴")
  class Meta():
    model = IdeaPost
    fields = '__all__'
    # ['title', 'content', 'devtools', 'interest', 'image', 'created_date', 'updated_date']

SWIDEA_SITE/server/apps/devtool_posts/views.py
from django.shortcuts import render, redirect
from .models import DevtoolPost
from .forms import DevtoolPostForm

def list(req):
  devtools = DevtoolPost.objects.all()
  search_txt = req.GET.get('search_txt')

  if search_txt:
    devtools = devtools.filter(name__contains = search_txt)
  ctx = {'devtools' : devtools}
  return render(req,'devtoolposts/list.html',ctx)

def create(req):
  if req.method == "GET":
    form = DevtoolPostForm
    ctx = {'form' : form}
    return render(req,'devtoolposts/create.html',ctx)
  
  form = DevtoolPostForm(req.POST)
  if form.is_valid():
    form.save()
  return redirect("devtools:list")

def detail(req, pk):
  devtool = DevtoolPost.objects.get(id=pk)

  if devtool:
    related_ideas = devtool.related_ideas.all()
  else:
    related_ideas = []

  ctx = {'devtool':devtool, 'related_ideas':related_ideas}
  return render(req,'devtoolposts/detail.html',ctx)

def delete(req, pk):
  DevtoolPost.objects.get(id=pk).delete()
  return redirect("devtools:list")

def update(req, pk):
  devtool = DevtoolPost.objects.get(id=pk)
  if req.method == "GET":
    form = DevtoolPostForm(instance=devtool)
    ctx = {'form':form, 'pk':pk}
    return render(req,'devtoolposts/update.html',ctx)
  
  form = DevtoolPostForm(req.POST, instance=devtool)
  if form.is_valid():
    form.save()

  return redirect("devtools:detail", pk)

SWIDEA_SITE/server/apps/idea_posts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import IdeaPost
from .forms import IdeaPostForm

def main(req):
  ideaposts = IdeaPost.objects.all()
  ctx = {'ideaposts' : ideaposts}
  return render(req, 'ideaposts/list.html',ctx)

def create(req):
  if req.method == "GET":
    ideaform = IdeaPostForm()
    ctx = {'ideaform':ideaform}
    return render(req, 'ideaposts/create.html',ctx)
  ideaform = IdeaPostForm(req.POST, req.FILES)
  if ideaform.is_valid():
    ideaform.save()
  return redirect("ideas:main")

def detail(req, pk):
  ideapost = IdeaPost.objects.get(id=pk)
  related_devtools = ideapost.devtools.related_ideas.all() if ideapost else []
  ctx = {'ideapost': ideapost, 'related_devtools': related_devtools}
  return render(req, 'ideaposts/detail.html', ctx)


def delete(req,pk):
  IdeaPost.objects.get(id=pk).delete()
  return redirect('ideas:main')

def update(req,pk):
  ideapost = IdeaPost.objects.get(id=pk)
  if req.method == "GET":
    ideaform = IdeaPostForm(instance=ideapost)
    ctx = {'ideaform' : ideaform, 'pk':pk}
    return render(req,'ideaposts/update.html',ctx)
  
  ideaform = IdeaPostForm(req.POST, req.FILES, instance=ideapost)
  if ideaform.is_valid():
    ideaform.save()
  return redirect("ideas:detail", pk)

SWIDEA_SITE/server/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="{%static 'idea_posts/css/style.css'%}">  
  {%block head%}


  {% endblock %}
</head>
<body>
  <main>
    <a href="/" id='logo' style='text-decoration: none; color: rgb(0, 255, 4);'><h1>☁️ Idea List ☁️</h1></a>
    <hr>
    {%block content%}
      
    
    {%endblock%}
  </main>
  <footer>
    <a href="{% url 'devtools:create' %}" class="mx-2">
      <button type="button" class="btn btn-info">개발툴 등록</button>
    </a>
    <a href="{% url 'devtools:list' %}" class="mx-2">
      <button type="button" class="btn btn-warning">개발툴 관리</button>
    </a>
  </footer>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

SWIDEA_SITE/server/templates/devtoolposts/create.html
<h2 style="color: green; font-size: 40px">DevTool Register</h2>
{%block head%}
  <title>devtoolposts_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'devtools:create' %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">submit</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/templates/devtoolposts/detail.html
{% load static %}

<h2 style="color: green; font-size: 40px">DevTool Detail</h2>

{% block content %}
  <h1 style="color: green; font-size: 40px">{{devtool.name}}</h1>
  <p>{{ devtool.kind }}</p>
  <h2 class="my-3">{{devtool.content}}</h2>

  <p>만들 수 있는 SW 목록</p>
  {% for rel_idea in related_ideas %}
    <a href="{% url 'ideaposts:detail' rel_idea.pk %}" class="btn btn-success">
      {{rel_idea.title}}
    </a>
  {% endfor %}

  <hr />
  <form action="{% url 'devtools:delete' devtool.pk %}" method="POST">
    {%csrf_token%}
    <a href="{% url 'devtools:update' devtool.pk %}" class="btn btn-primary">수정</a>
    <button type="submit" class="btn btn-danger">삭제</button>
  </form>
  <a href="{% url 'devtools:list' %}" class="btn btn-primary">목록</a>
{% endblock content %}

SWIDEA_SITE/server/templates/devtoolposts/list.html
{% load static %}

{%block head%}
  <title>DevTool List</title>
{%endblock%}

<h2>DevTool List</h2>

{%block content%}
  <div class="content-wrapper">
    <!-- 개발툴 목록 -->
    {% for devtool in devtools %}
    <div class="devtools">
      <a href="{% url 'devtools:detail' devtool.pk %}" class="name">
        {{devtool.name}}
      </a>
      <p class="kind">{{ devtool.kind }}</p>
      <p class="content">{{ devtool.content }}</p>
    </div>
    {% endfor %}
  </div>
{%endblock%}

SWIDEA_SITE/server/templates/devtoolposts/update.html
{%block head %}
  <title>devtoolposts_update</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'devtools:update' pk %}"
    method="post"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
  <hr>
  <form
    action="{% url 'devtools:delete' pk %}"
    method="post"
  >
    {%csrf_token%}
    <button class="btn btn-danger">삭제</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/templates/ideaposts/create.html
{% extends 'base.html' %}
{%block head%}
  <title>ideapost_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'ideas:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{ideaform.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
{%endblock%}

SWIDEA_SITE/server/templates/ideaposts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 style="color: green; font-size: 40px">{{ideapost.title}}</h1>
  {% if ideapost.image.url != '' %}
    <img src="{{ideapost.image.url}}" alt="아이디어 이미지" />
  {% else %}
    <img src="{% static 'idea_posts/image/no_img.png' %}" alt="대체 텍스트" />
  {% endif %}
  <p>아이디어 관심도: {{ideapost.interest}}</p>
  <p>예상 개발툴:</p>
  {% if idea.devtools %}
    <p><a href="{% url 'devtool_detail' ideapost.devtools.pk %}">{{ ideapost.devtools.name }}</a></p>
  {% else %}
    <p>개발 도구가 지정되지 않았습니다.</p>
  {% endif %}
  <h2 class="my-3">{{ideapost.content}}</h2>
  <p>작성일: {{ideapost.created_date}}</p>
  <p>수정일: {{ideapost.updated_date}}</p>

  <hr />
  <form action="{% url 'ideas:delete' ideapost.pk %}" method="POST">
    {%csrf_token%}
    <a href="{% url 'ideas:update' ideapost.pk %}" class="btn btn-primary">수정</a>
    <button type="submit" class="btn btn-danger">삭제</button>
  </form>
  <a href="{% url 'ideas:main' %}" class="btn btn-primary">목록</a>
{% endblock content %}

SWIDEA_SITE/server/templates/ideaposts/list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>Idea List</title>
{%endblock%}

{%block content%}
  <div class="search-box">    
    <a href="{% url 'ideas:create' %}" class = 'btn btn-secondary mx-2'>글 생성</a>
  </div>

  <div class="content-wrapper">
    <!-- 글 목록 -->
    {% for ideapost in ideaposts %}
    <div class="item">
      {% if ideapost.image.url != null and ideapost.image.url != '' %}
        <img src="{{ideapost.image.url}}" alt="대체텍스트">
      {% else %}
        <img src="{% static 'idea_posts/image/no_img.png' %}" alt="">
      {% endif %}
      <div class="info">
        <a href="{% url 'ideas:detail' ideapost.pk%}" class="title">
          {{ideapost.title}}
        </a>
        <p class="devtools">예상 개발 툴 : {{ideapost.devtools_id}}</p>
        <p class="interest">아이디어 관심도 : {{ideapost.interest}}</p>
      </div>
    </div>
  {% endfor %}
  </div>
{%endblock%}

SWIDEA_SITE/server/templates/ideaposts/update.html
{% extends 'base.html' %}

{%block head %}
  <title>ideapost_update</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'ideas:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{ideaform.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
{%endblock%}